"""init_migrate2

Revision ID: 69637f739109
Revises: 320f7adfdd70
Create Date: 2024-02-12 14:46:09.802176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69637f739109'
down_revision = '320f7adfdd70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
