"""initial5

Revision ID: 746ab088b501
Revises: ae5a6cf566e3
Create Date: 2024-02-13 13:55:27.704813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "746ab088b501"
down_revision = "ae5a6cf566e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("receipts", sa.Column("payment_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "receipts", "payments", ["payment_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "receipts", type_="foreignkey")
    op.drop_column("receipts", "payment_id")
    # ### end Alembic commands ###
