"""initial4

Revision ID: ae5a6cf566e3
Revises: 442bd3335cfa
Create Date: 2024-02-13 13:52:16.300185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ae5a6cf566e3"
down_revision = "442bd3335cfa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("payments_user_id_fkey", "payments", type_="foreignkey")
    op.drop_column("payments", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "payments_user_id_fkey", "payments", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
